
  
  ######################################### SET USER DEFINED ARGUMENTS ####################################################################
filtering_arguments: 
  buildstock_file: baseline_metadata_only.csv              # must be generated (derived) by resstock-euss.2022.1 version of ResStock
  # "buildstock_file": "baseline_metadata_only_example_subset.csv" # must be generated (derived) by resstock-euss.2022.1 version of ResStock
  buildstock_output_file: LA_Detroit_buildstock_24.03.23.csv

  buildstock_folder": /Users/camilotoruno/Documents/GitHub/building_energy_modeling

  # "buildstock_output_folder: os.path.join(os.path.sep Volumes seas-mtcraig EPWFromTGW) 
  buildstock_output_folder: /Users/camilotoruno/Documents/local_research_data 
  # buildstock_output_folder: os.path.join(os.path.sep Users ctoruno Documents local_research_data) 

  federal_poverty_levels: ['0-100%', '100-150%', '150-200%']   # federal poverty levels to match format of buildstock_file
  statistical_sample_size: 400         
      # statistically representative sample size for a city. DOES NOT DEFINE CITY SIZE LIMIT.
      # Defines what we consider a statistically representative sample size then scales the number of 
      # buildings to reach a proprtionally statistically representative sample by federal poverty level. 
      # See discussion in ASSET Lab

  keep_cities: [
    # "AZ, Phoenix",
    "CA, Los Angeles",
    # "CO, Denver",
    # "FL, Orlando",
    # "GA, Atlanta",
    # "ID, Boise City",
    # "IL, Chicago",
    # "KS, Kansas City",
    # "MA, Boston",
    "MI, Detroit",
    # "MN, Minneapolis",
    # "NE, Omaha",
    # "NY, New York",
    # "PA, Philadelphia",
    # "TX, Dallas"
    ]

  exclude_cities: ['In another census Place', 'Not in a census Place']     # can be an empty list


oedi_querying_arguments:
  oedi_download_folder: filtering_arguments['buildstock_output_folder']
  bldg_download_folder_basename: 'bldgs_idf_output_flags'                               # set as desired. Root name for folder of generated files
  unzip: True      # default False
  

epw_data:
  # Mac Example
  # weather_folder: /Users/camilotoruno/Documents/GitHub/EnergyPlus-Python/TGWEPWs_trimmed
  # weather_folder: os.path.join(os.path.sep Users camilotoruno Documents ctoruno weather) 

  # # Windows example
  # weather_folder: os.path.join(os.path.sep Users ctoruno Documents local_research_data weather)

  # Turbo location 
  weather_folder: /Volumes/seas-mtcraig/EPWFromTGW/TGWEPWs 
  # weather_folder: os.path.join(os.path.sep Z: EPWFromTGW TGWEPWs) 

  scenario_folders: [historical_1980-2020, rcp45cooler_2020-2060] #, rcp45hotter_2020-2060, rcp85cooler_2020-2060]
  

openstudio_workflow_arguments:
  # Mac example
  openstudio_path: /usr/local/bin/openstudio        # Set to local path. Requires openstudio version 3.4.0 in bin
  openstudio_application_path: /Applications/OpenStudio-3.4.0  # set the OpenStudio application path to your downloaded copy. Requires OpenStudio 3.4.0

  # # Windows example 
  # openstudio_path: os.path.join(os.path.sep openstudio-3.4.0 bin openstudio.exe)        # Set to local path. Requires openstudio version 3.4.0 in bin
  # openstudio_application_path:  os.path.join(os.path.sep openstudio-3.4.0)   # set the OpenStudio application path to your downloaded copy. Requires OpenStudio 3.4.0
  

# Define the desired output file settings
new_Output_Control_Files:
  field: 'OutputControl:Files'
  options: [
    # turn on (OpenStudio defaults of no)
    {'Output_MTR': 'Yes'},     

    {'Output_ESO': 'Yes'},      

    # turn off (OpenStudio defaults of yes)
    {'Output_Tabular': 'No'},   

    {'Output_SQLite': 'No'},     

    {'Output_JSON': 'No'},
    ]


new_Output_Variables:
  field: Output:Variable 
  options: [
    {Key_Value: "*": ,
    Zone Air Temperature: Variable_Name,
    Reporting_Frequency: Hourly},

    {Key_Value: *: Key_Value,
    Variable_Name: "Site Outdoor Air Wetbulb Temperature",
    Reporting_Frequency: Timestep},

    {Key_Value: *: Key_Value,
    Variable_Name: "Zone Air Relative Humidity",
    Reporting_Frequency: Daily},

    {Key_Value: *: Key_Value,
    Variable_Name: "Zone Air Relative Humidity",
    Reporting_Frequency: Hourly},

    {Key_Value: "*",
    Variable_Name: Site Outdoor Air Drybulb Temperature,
    Reporting_Frequency: Monthly}
      ]

new_Output_Meters:
  field: Output:Meter 
  options: [
    {Key_Name: Electricity:Facility,
    Reporting_Frequency: Timestep},

    {Key_Name: NaturalGas:Facility,
    Reporting_Frequency: Timestep},

    {Key_Name: DistrictCooling:Facility,
    Reporting_Frequency: Timestep},

    {Key_Name: DistrictHeatingWater:Facility:,
    Reporting_Frequency: Timestep}
    ]
  
new_Outputs_MeterFileOnly:
  field: Output:Meter:MeterFileOnly 
  options: [
    {Key_Name: NaturalGas:Facility,
    Reporting_Frequency: Daily},

    {Key_Name: Electricity:Facility,
    Reporting_Frequency: Timestep},

    {Key_Name: Electricity:Facility,
    Reporting_Frequency: Daily}
    ]
  
misc_arguments:
  # set the location of your virtual environment 
  # Mac example
  conda_venv_dir: /Users/camilotoruno/anaconda3/envs/research 

  # # Windows example
  # conda_venv_dir: os.path.join(os.path.sep Users ctoruno AppData Local anaconda3 envs ResStock2EnergyPlus)

  verbose: False
  overwrite_output: True
  cwd: cwd
  max_cpu_load: 0.99      # must be in the range [0, 1]. The value 1 indidcates all CPU cores, 0 indicates 1 CPU core
		